name: RizzyVPN Auto-Updater

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:      # Можно запустить вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq python3 python3-pip
          pip3 install requests feedparser beautifulsoup4

      - name: Запуск обновления сабки
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
        run: |
          python3 /home/runner/work/RizzyVPN-t.me-RizzyVPN/RizzyVPN-t.me-RizzyVPN/.github/workflows/update_sabka.py

      - name: Коммит изменений
        run: |
          git config user.name "RizzyVPN Bot"
          git config user.email "bot@rizzyvpn.t.me"
          git add RizzyVPN-Free.txt counter.txt
          git diff --staged --quiet || git commit -m "Автообновление сабки"
          git push
